services:
  - type: web
    name: statsbase-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn main:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.13
